### ISSUE TITLE
Lost "settings" app

### ISSUE THREAD

**Issue by wajda** [khlam/debloat-samsung-android#10]
Hi,
On Samsung A5 2017, after applying the entire `commands.txt` the settings don't open anymore.
When tapping on the gears icon on the top panel an error window appears with the message "Settings has stopped.". No more details.

I presume one of the packages was mandatory and has to be re-installed.
How can I figure out what package is missing and how to revert it back?

Thanks.

**Comment by wajda** [comment]
Not sure if it's related, but there is a suspicious exception in the system logs, when trying to open "settings":
```
01-01 23:38:21.136 16540 16560 I TileUtils: updateTileData applicationInfo.isSystemApp() : true, activityInfo.packageName : com.android.settings, SETTING_PKG : com.android.settings
01-01 23:38:21.141 16540 16540 D AndroidRuntime: Shutting down VM
01-01 23:38:21.142 16540 16540 E AndroidRuntime: FATAL EXCEPTION: main
01-01 23:38:21.142 16540 16540 E AndroidRuntime: Process: com.android.settings, PID: 16540
01-01 23:38:21.142 16540 16540 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.android.settings/com.android.settings.Settings}: java.lang.SecurityException: Failed to find provider user_dictionary for user 0; expected to find a valid ContentProvider for this authority
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3790)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6944)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: Caused by: java.lang.SecurityException: Failed to find provider user_dictionary for user 0; expected to find a valid ContentProvider for this authority
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1967)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1913)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:788)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1930)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1919)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at com.android.settings.search.DynamicIndexableContentMonitor$InputMethodServicesMonitor.initialize(DynamicIndexableContentMonitor.java:450)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at com.android.settings.search.DynamicIndexableContentMonitor.register(DynamicIndexableContentMonitor.java:149)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at com.android.settings.search.DynamicIndexableContentMonitor.register(DynamicIndexableContentMonitor.java:117)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at com.android.settings.SettingsActivity.onResume(SettingsActivity.java:1733)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at com.android.settings.Settings.onResume(Settings.java:66)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:7415)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)
01-01 23:38:21.142 16540 16540 E AndroidRuntime: 	... 10 more
```

**Comment by gazataeon** [comment]
Try reinstalling these 

`pm install-existing com.sec.imsservice`
 `pm install-existing com.osp.app.signin`

**Comment by IllicitMoonshine** [comment]
> Try reinstalling these
> 
> `pm install-existing com.sec.imsservice`
> `pm install-existing com.osp.app.signin`

I was having a similar issue and this solved it.  It also solved my issue of not being able to get a cellular connection.

**Comment by cjom** [comment]
> 
> 
> Try reinstalling these
> 
> `pm install-existing com.sec.imsservice` `pm install-existing com.osp.app.signin`

I couldn't get contact groups (I wanted to set custom ringtones by groups) and this sent me into the right path.
com.osp.app.signin  is needed for contact groups!

com.sec.imsservice is not needed.

This happens in Samsung A52s 5G
